version: '2'
services:

  mysql:
    image: mysql:8.0
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: storm_root_password
      MYSQL_DATABASE: storm_database
      MYSQL_USER: storm_user
      MYSQL_PASSWORD: storm_password

  backend:
    build: ./backend
    links:
      - mysql
    ports:
      - "8081:8080"
    volumes:
      - ./backend/sample:/sample
    entrypoint: python3 -m sample.server

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    entrypoint: /app/run.sh

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - backend
      - frontend
    entrypoint: nginx
